#!/bin/bash

#SBATCH --job-name=train
#SBATCH --output=./outs/%x.jobid-%j.out
#SBATCH --nodes=1
#SBATCH --partition=gpu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --gpus=1
#SBATCH --time=7-00:00:00

module load anaconda3

source activate food-regression

cd /project/jakarin.c/food-regression/

SECONDS=0

python call.py

duration=$SECONDS
echo "$(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed."